[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

# Enables the usage of setuptools_scm
[tool.setuptools_scm]
"root" = "."

[tool.isort]
profile = "black"
skip_glob = ["src/usdb_syncer/gui/forms", "src/usdb_syncer/gui/resources"]

[tool.black]
skip-magic-trailing-comma = true
preview = true

[tool.pylint.master]
ignore-paths = [
    "src/usdb_syncer/gui/forms",
    "src/usdb_syncer/gui/resources",
    "venv",
    ".tox",
]
# Add McCabe code complexity checker
load-plugins = "pylint.extensions.mccabe"

[tool.pylint.basic]
good-names = ["mw", "p1", "p2", "closeEvent", "customEvent"]

[tool.pylint.messages_control]
extension-pkg-whitelist = ["PySide6"]
disable = [
    "too-few-public-methods",
    "logging-fstring-interpolation",
    "too-many-instance-attributes",
    "too-many-arguments",
    "missing-function-docstring",
    "too-many-return-statements",
    "duplicate-code",
    "too-many-public-methods",
    "line-too-long",
]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
follow_imports = "silent"
exclude = ["src/usdb_syncer/gui/forms", "src/usdb_syncer/gui/resources"]

[tool.pyright]
# generates a lot of false positives for mutagen
reportPrivateImportUsage = false
exclude = [
    "src/usdb_syncer/gui/forms",
    "src/usdb_syncer/gui/resources",
    "venv",
    ".tox",
]
